Initializing North Robot...
Physical initialization of North Robot...
Moving robot to home position
   vial_index           vial_name         location  location_index  vial_volume  capped cap_type vial_type    home_location  home_location_index
0           0  measurement_vial_0    main_8mL_rack               0         7.08    True     open      8_mL    main_8mL_rack                    0
1           1  measurement_vial_1            clamp               0         6.80    True     open      8_mL    main_8mL_rack                    1
2           2  measurement_vial_2    main_8mL_rack               2         0.00    True     open      8_mL    main_8mL_rack                    2
3           3       liquid_source  large_vial_rack               2        20.00    True     open     20_mL  large_vial_rack                    2
Visualizing...
Only hit enter if the status of the vials (including open/close) is correct, otherwise hit ctrl-c--Wellplate status-- 
 Wellplate type: 48 WELL PLATE 
 Number in source: 0 
 Number in waste: 0 
 NR Pipetting area occupied: True
Only hit enter if the status of the well plates is correct, otherwise hit ctrl-cC:\Users\owenm\OneDrive\Desktop\Python\Baybe\.conda\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Traceback (most recent call last):
  File "c:\Users\owenm\OneDrive\Desktop\North Robotics\utoronto_demo\utoronto_demo\workflows\calibration_sdl_short_abs.py", line 117, in <module>
    suggestions = recommender.get_suggestions(ax_client, volume, n=SOBOL_CYCLES_PER_VOLUME)
  File "C:\Users\owenm\OneDrive\Desktop\North Robotics\utoronto_demo\utoronto_demo\../utoronto_demo\recommenders\pipeting_optimizer_honegumi.py", line 89, in get_suggestions
    params, trial_index = ax_client.get_next_trial(
  File "C:\Users\owenm\OneDrive\Desktop\Python\Baybe\.conda\lib\site-packages\ax\utils\common\executils.py", line 167, in actual_wrapper
    return func(*args, **kwargs)
  File "C:\Users\owenm\OneDrive\Desktop\Python\Baybe\.conda\lib\site-packages\ax\service\ax_client.py", line 554, in get_next_trial
    raise e
  File "C:\Users\owenm\OneDrive\Desktop\Python\Baybe\.conda\lib\site-packages\ax\service\ax_client.py", line 543, in get_next_trial
    generator_run=self._gen_new_generator_run(
  File "C:\Users\owenm\OneDrive\Desktop\Python\Baybe\.conda\lib\site-packages\ax\service\ax_client.py", line 1781, in _gen_new_generator_run
    return not_none(self.generation_strategy).gen(
  File "C:\Users\owenm\OneDrive\Desktop\Python\Baybe\.conda\lib\site-packages\ax\modelbridge\generation_strategy.py", line 372, in gen
    return self._gen_multiple(
  File "C:\Users\owenm\OneDrive\Desktop\Python\Baybe\.conda\lib\site-packages\ax\modelbridge\generation_strategy.py", line 777, in _gen_multiple
    gr_limit = self._curr.generator_run_limit(raise_generation_errors=True)
  File "C:\Users\owenm\OneDrive\Desktop\Python\Baybe\.conda\lib\site-packages\ax\modelbridge\generation_node.py", line 581, in generator_run_limit
    criterion.block_continued_generation_error(
  File "C:\Users\owenm\OneDrive\Desktop\Python\Baybe\.conda\lib\site-packages\ax\modelbridge\transition_criterion.py", line 393, in block_continued_generation_error
    raise MaxParallelismReachedException(
ax.exceptions.generation_strategy.MaxParallelismReachedException: Maximum parallelism for generation node #GenerationStep_0 (Sobol) has been reached: 1 trials are currently 'running'. Some trials need to be completed before more trials can be generated. See https://ax.dev/docs/bayesopt.html to understand why limited parallelism improves performance of Bayesian optimization.
