Initializing North Robot...
Physical initialization of North Robot...
Moving robot to home position
   vial_index           vial_name         location  location_index  vial_volume  capped cap_type vial_type    home_location  home_location_index
0           0  measurement_vial_0    main_8mL_rack               0         7.08    True     open      8_mL    main_8mL_rack                    0
1           1  measurement_vial_1            clamp               0         6.80    True     open      8_mL    main_8mL_rack                    1
2           2  measurement_vial_2    main_8mL_rack               2         0.00    True     open      8_mL    main_8mL_rack                    2
3           3       liquid_source  large_vial_rack               2        20.00    True     open     20_mL  large_vial_rack                    2
Visualizing...
Only hit enter if the status of the vials (including open/close) is correct, otherwise hit ctrl-c--Wellplate status-- 
 Wellplate type: 48 WELL PLATE 
 Number in source: 0 
 Number in waste: 0 
 NR Pipetting area occupied: True
Only hit enter if the status of the well plates is correct, otherwise hit ctrl-cC:\Users\owenm\OneDrive\Desktop\Python\Baybe\.conda\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
C:\Users\owenm\OneDrive\Desktop\Python\Baybe\.conda\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
C:\Users\owenm\OneDrive\Desktop\Python\Baybe\.conda\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
C:\Users\owenm\OneDrive\Desktop\Python\Baybe\.conda\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
C:\Users\owenm\OneDrive\Desktop\Python\Baybe\.conda\lib\site-packages\ax\modelbridge\cross_validation.py:463: UserWarning: Encountered exception in computing model fit quality: RandomModelBridge does not support prediction.
  warn("Encountered exception in computing model fit quality: " + str(e))
Getting pipet number: 3 from rack 1
Pipetting from vial liquid_source, amount: 0.01 mL
Aspirating 0.07656387686729432 mL then waiting 0 s
Aspirating 0.01 mL then waiting 22.48070776462555 s
Aspirating 0.03626673817634583 mL then waiting 0 s
Transferring 0.01 mL into well #0 of 96 WELL PLATE
Dispensing 0.12283061504364014 mL then waiting 5.529413223266602 s
Transferring 0.01 mL into well #1 of 96 WELL PLATE
Dispensing 0.12283061504364014 mL then waiting 5.529413223266602 s
Transferring 0.01 mL into well #2 of 96 WELL PLATE
Dispensing 0.12283061504364014 mL then waiting 5.529413223266602 s
Pipetting from vial liquid_source, amount: 0.01 mL
Aspirating 0.07656387686729432 mL then waiting 0 s
Aspirating 0.01 mL then waiting 22.48070776462555 s
Aspirating 0.03626673817634583 mL then waiting 0 s
Transferring 0.01 mL into well #0 of 96 WELL PLATE
Dispensing 0.12283061504364014 mL then waiting 5.529413223266602 s
Transferring 0.01 mL into well #1 of 96 WELL PLATE
Dispensing 0.12283061504364014 mL then waiting 5.529413223266602 s
Transferring 0.01 mL into well #2 of 96 WELL PLATE
Dispensing 0.12283061504364014 mL then waiting 5.529413223266602 s
Pipetting from vial liquid_source, amount: 0.01 mL
Aspirating 0.07656387686729432 mL then waiting 0 s
Aspirating 0.01 mL then waiting 22.48070776462555 s
Aspirating 0.03626673817634583 mL then waiting 0 s
Transferring 0.01 mL into well #0 of 96 WELL PLATE
Dispensing 0.12283061504364014 mL then waiting 5.529413223266602 s
Transferring 0.01 mL into well #1 of 96 WELL PLATE
Dispensing 0.12283061504364014 mL then waiting 5.529413223266602 s
Transferring 0.01 mL into well #2 of 96 WELL PLATE
Dispensing 0.12283061504364014 mL then waiting 5.529413223266602 s
Traceback (most recent call last):
  File "c:\Users\owenm\OneDrive\Desktop\North Robotics\utoronto_demo\utoronto_demo\workflows\calibration_sdl_short_abs.py", line 123, in <module>
    time = dispense_into_wp(lash_e, 'liquid_source', volume, params, wells, NEW_PIPET_EACH_TIME_SET)
  File "c:\Users\owenm\OneDrive\Desktop\North Robotics\utoronto_demo\utoronto_demo\workflows\calibration_sdl_short_abs.py", line 72, in dispense_into_wp
    start = time.time()
AttributeError: 'float' object has no attribute 'time'
